/**
 * seed-data.js
 * All demo personas and per-user data definitions for StartSmart.
 * Imported by seed-demo.js (multi-user Admin API) and seed-single.js (single user).
 */

// ── Tag palette (matches src/utils/tagUtils.js preset colors) ────────────────
export const TAG_PALETTE = [
  { name: 'Work',       color: '#2563eb' },
  { name: 'Tech',       color: '#0e7490' },
  { name: 'Study',      color: '#c2610c' },
  { name: 'Creative',   color: '#be185d' },
  { name: 'Planning',   color: '#a16207' },
  { name: 'Health',     color: '#16a34a' },
  { name: 'Urgent',     color: '#b91c1c' },
  { name: 'Personal',   color: '#16a34a' },
  { name: 'Design',     color: '#be185d' },
  { name: 'Research',   color: '#c2610c' },
  { name: 'Backend',    color: '#0e7490' },
  { name: 'Frontend',   color: '#0e7490' },
  { name: 'Meeting',    color: '#a16207' },
  { name: 'Writing',    color: '#be185d' },
  { name: 'Review',     color: '#2563eb' },
  { name: 'Fitness',    color: '#16a34a' },
];

// ── Demo personas ─────────────────────────────────────────────────────────────
export const PERSONAS = [
  {
    email:      'maya.cohen.demo@startsmart.app',
    password:   'Demo2026!Maya',
    first_name: 'Maya',
    last_name:  'Cohen',
    username:   'maya_cohen',
    phone:      '+972-50-123-4567',
    bio:        'Senior Software Engineer at TechFlow. I use StartSmart to stay on top of feature work and avoid the trap of endless meetings.',
    language:   'en',
    theme:      'dark',
    timezone:   'Asia/Jerusalem',
    avatar_color: '#6b38d4',
    plan:       'pro',
    tags:       ['Work', 'Tech', 'Urgent', 'Planning', 'Backend', 'Frontend', 'Review', 'Meeting'],
    task_mix:   'engineer',
  },
  {
    email:      'arjun.patel.demo@startsmart.app',
    password:   'Demo2026!Arjun',
    first_name: 'Arjun',
    last_name:  'Patel',
    username:   'arjun_pm',
    phone:      '+91-98-7654-3210',
    bio:        'Product Manager at Nexus Labs. I track every sprint item and cross-team dependency in StartSmart. No more missed deadlines.',
    language:   'en',
    theme:      'light',
    timezone:   'Asia/Kolkata',
    avatar_color: '#2563eb',
    plan:       'premium',
    tags:       ['Work', 'Planning', 'Meeting', 'Urgent', 'Research', 'Review', 'Creative', 'Personal'],
    task_mix:   'pm',
  },
  {
    email:      'sara.jensen.demo@startsmart.app',
    password:   'Demo2026!Sara',
    first_name: 'Sara',
    last_name:  'Jensen',
    username:   'sara_studies',
    phone:      null,
    bio:        'Computer Science student at TU Berlin. Balancing coursework, research, and side projects. StartSmart keeps me from losing track.',
    language:   'de',
    theme:      'light',
    timezone:   'Europe/Berlin',
    avatar_color: '#c2610c',
    plan:       'free',
    tags:       ['Study', 'Tech', 'Research', 'Creative', 'Health', 'Personal', 'Urgent', 'Planning'],
    task_mix:   'student',
  },
  {
    email:      'carlos.mendez.demo@startsmart.app',
    password:   'Demo2026!Carlos',
    first_name: 'Carlos',
    last_name:  'Mendez',
    username:   'carlos_freelance',
    phone:      '+1-305-555-0198',
    bio:        'Freelance full-stack developer & consultant. Managing 4 active client projects. Billing accuracy depends on time tracking.',
    language:   'en',
    theme:      'dark',
    timezone:   'America/New_York',
    avatar_color: '#16a34a',
    plan:       'pro',
    tags:       ['Work', 'Tech', 'Urgent', 'Creative', 'Planning', 'Personal', 'Backend', 'Frontend'],
    task_mix:   'freelancer',
  },
  {
    email:      'yuki.tanaka.demo@startsmart.app',
    password:   'Demo2026!Yuki',
    first_name: 'Yuki',
    last_name:  'Tanaka',
    username:   'yuki_designs',
    phone:      '+81-90-1234-5678',
    bio:        'UI/UX Designer at Studio Pixel. I track design sprints, client feedback cycles, and personal creative projects all in one place.',
    language:   'en',
    theme:      'light',
    timezone:   'Asia/Tokyo',
    avatar_color: '#be185d',
    plan:       'free',
    tags:       ['Design', 'Creative', 'Work', 'Research', 'Planning', 'Urgent', 'Meeting', 'Writing'],
    task_mix:   'designer',
  },
];

// ── User settings defaults per persona ───────────────────────────────────────
export const SETTINGS_BY_PLAN = {
  free:    { daily_goal_hours: 4, default_estimate_minutes: 30 },
  pro:     { daily_goal_hours: 6, default_estimate_minutes: 45 },
  premium: { daily_goal_hours: 8, default_estimate_minutes: 60 },
};

// ── Task templates per persona ────────────────────────────────────────────────
// Each entry: { title, description, estimatedMinutes, tagNames[], priorityHigh }

export const TASK_TEMPLATES = {
  engineer: {
    completed: [
      { title: 'Implement JWT refresh token rotation',          desc: 'Add automatic refresh with 15-minute expiry and rotation on every use.',           est: 90,  tags: ['Backend','Urgent'],  hi: true  },
      { title: 'Write unit tests for auth middleware',          desc: 'Cover edge cases: expired token, missing header, invalid signature.',               est: 60,  tags: ['Backend','Review'],  hi: false },
      { title: 'Refactor database connection pool',             desc: 'Move from static pool to dynamic sizing based on request queue depth.',             est: 75,  tags: ['Backend','Tech'],    hi: false },
      { title: 'Set up CI/CD pipeline with GitHub Actions',     desc: 'Build, test, lint and deploy to staging on every PR merge.',                        est: 120, tags: ['Tech','Work'],       hi: true  },
      { title: 'Fix memory leak in WebSocket handler',          desc: 'Subscriptions not cleaned up on disconnect. Track with heap snapshot.',             est: 45,  tags: ['Backend','Urgent'],  hi: true  },
      { title: 'Code review: payment service PR',               desc: 'Review stripe integration, error handling, and idempotency key usage.',             est: 30,  tags: ['Review','Work'],     hi: false },
      { title: 'Migrate user table to new schema',              desc: 'Add soft delete, audit columns, and backfill existing rows.',                        est: 60,  tags: ['Backend','Urgent'],  hi: true  },
      { title: 'Implement rate limiting middleware',            desc: 'Token bucket per IP and per user. Redis-backed with sliding window.',                est: 90,  tags: ['Backend','Tech'],    hi: false },
      { title: 'Update API documentation in Swagger',           desc: 'All new endpoints from Q2 sprint need doc coverage.',                               est: 45,  tags: ['Work','Review'],     hi: false },
      { title: 'Set up Redis caching for leaderboard',          desc: 'Cache with 30s TTL, invalidate on score change.',                                   est: 60,  tags: ['Backend','Tech'],    hi: false },
      { title: 'Frontend: implement dark mode toggle',          desc: 'Use CSS custom properties, persist preference to localStorage + profile.',           est: 45,  tags: ['Frontend','Tech'],   hi: false },
      { title: 'Fix mobile layout in task list view',           desc: 'Cards overflow on 375px viewports. Needs responsive flexbox fix.',                  est: 30,  tags: ['Frontend','Urgent'], hi: true  },
      { title: 'Quarterly performance review self-assessment',  desc: 'Document impact, challenges and goals for H2.',                                     est: 60,  tags: ['Work','Planning'],   hi: false },
      { title: 'Onboard new team member: code walkthrough',     desc: 'Walk through monorepo structure, coding standards and deployment process.',         est: 90,  tags: ['Work','Meeting'],    hi: false },
      { title: 'Implement search with full-text indexing',      desc: 'PostgreSQL tsvector on title and body. GIN index for fast lookup.',                 est: 75,  tags: ['Backend','Tech'],    hi: false },
      { title: 'Sprint retrospective: prepare action items',    desc: 'Collect team feedback and define measurable improvements for next sprint.',         est: 30,  tags: ['Meeting','Planning'], hi: false },
      { title: 'Patch CVE-2025-3891 in dependency',            desc: 'Urgent: update lodash to latest, run full regression.',                             est: 20,  tags: ['Urgent','Tech'],     hi: true  },
      { title: 'Integrate Sentry error tracking',               desc: 'Add to all services. Set up alerts for critical errors.',                           est: 45,  tags: ['Tech','Work'],       hi: false },
      { title: 'Add pagination to task history API',            desc: 'Cursor-based pagination. Default 25 items. Include total count.',                   est: 60,  tags: ['Backend','Review'],  hi: false },
      { title: 'Weekly 1:1 prep with engineering lead',         desc: 'Review blockers, capacity and roadmap alignment.',                                  est: 20,  tags: ['Meeting','Work'],    hi: false },
    ],
    in_progress: [
      { title: 'Implement real-time notifications with WebSockets', desc: 'Server-Sent Events or WebSocket — evaluate latency and scaling.',         est: 120, tags: ['Backend','Frontend'], hi: true  },
      { title: 'Design data export feature',                        desc: 'JSON and CSV. Include all user data per GDPR Article 20.',                est: 75,  tags: ['Backend','Work'],     hi: false },
      { title: 'Refactor frontend state management',                desc: 'Move from prop drilling to Context API. Evaluate Zustand for complex state.', est: 90, tags: ['Frontend','Tech'], hi: false },
      { title: 'Write API integration tests',                       desc: '80% endpoint coverage using supertest. Mock external services.',          est: 60,  tags: ['Backend','Review'],   hi: false },
      { title: 'Implement multi-tenant architecture',               desc: 'Isolate data per org. Schema-per-tenant vs row-level security.',          est: 180, tags: ['Backend','Urgent'],   hi: true  },
      { title: 'Performance audit: reduce TTI',                     desc: 'Time to Interactive > 4s on 3G. Code-split routes, lazy-load images.',   est: 90,  tags: ['Frontend','Urgent'],  hi: true  },
    ],
    pending: [
      { title: 'Plan Q3 technical roadmap',                    desc: 'Align with PM on priority features and technical debt ratio.',                est: 90,  tags: ['Planning','Work'],    hi: false },
      { title: 'Set up feature flag system',                   desc: 'Use LaunchDarkly or homegrown. Gradual rollouts and A/B tests.',             est: 60,  tags: ['Tech','Work'],        hi: false },
      { title: 'Implement automated database backups',         desc: 'Daily snapshot to S3. Test restoration procedure.',                         est: 45,  tags: ['Backend','Planning'],  hi: false },
      { title: 'Contribute to open-source: fix issue #1892',  desc: 'Good first issue. Fix timezone parsing edge case in date-fns.',             est: 60,  tags: ['Tech','Personal'],    hi: false },
      { title: 'Team tech talk: TypeScript advanced patterns', desc: 'Conditional types, mapped types, template literals.',                       est: 90,  tags: ['Work','Tech'],        hi: false },
      { title: 'Set up load testing with k6',                  desc: 'Simulate 1000 concurrent users. Find bottlenecks before Q3 launch.',       est: 60,  tags: ['Backend','Urgent'],   hi: true  },
      { title: 'Review and update CORS policy',                desc: 'Audit allowed origins. Tighten for production domains.',                    est: 30,  tags: ['Backend','Review'],   hi: false },
      { title: 'Implement GraphQL subscriptions',              desc: 'Real-time data for dashboard widgets using subscription resolvers.',        est: 120, tags: ['Backend','Tech'],     hi: false },
      { title: 'Annual security audit prep',                   desc: 'Gather evidence for OWASP compliance checklist.',                          est: 90,  tags: ['Work','Urgent'],      hi: true  },
      { title: 'Evaluate edge caching with Cloudflare Workers',desc: 'Prototype static asset delivery and A/B test latency improvement.',       est: 90,  tags: ['Tech','Planning'],    hi: false },
    ],
  },

  pm: {
    completed: [
      { title: 'Write PRD: AI-powered task suggestions',        desc: 'Define user stories, success metrics and rollout plan.',                    est: 120, tags: ['Work','Research'],    hi: true  },
      { title: 'Conduct user interviews: onboarding flow',      desc: '8 interviews. Synthesize friction points and drop-off reasons.',           est: 90,  tags: ['Research','Work'],    hi: false },
      { title: 'Q2 OKR review presentation',                    desc: 'Present progress, blockers and revised targets to leadership.',            est: 60,  tags: ['Work','Planning'],    hi: true  },
      { title: 'Competitive analysis: Notion vs Linear',        desc: 'Feature matrix, pricing, ICP fit and differentiation opportunities.',     est: 90,  tags: ['Research','Work'],    hi: false },
      { title: 'Sprint planning: Q3 feature set',               desc: 'Prioritize backlog with RICE framework. Align engineering estimates.',     est: 60,  tags: ['Planning','Meeting'],  hi: false },
      { title: 'Write product changelog for June release',      desc: 'User-facing release notes highlighting top 5 features.',                  est: 30,  tags: ['Work','Creative'],    hi: false },
      { title: 'Define north star metric',                      desc: 'Workshop with leadership. Land on DAU/MAU × depth of use.',               est: 45,  tags: ['Research','Planning'], hi: false },
      { title: 'Analyse churn: Q1 cohort',                      desc: 'Identify top 3 cancellation reasons. Propose retention experiments.',      est: 90,  tags: ['Research','Urgent'],  hi: true  },
      { title: 'Design experiment: pricing page redesign',      desc: 'Hypothesis, success metrics, rollout plan and sample size.',              est: 60,  tags: ['Creative','Work'],    hi: false },
      { title: 'Stakeholder update: roadmap alignment',         desc: 'Monthly update to C-suite and key stakeholders.',                        est: 45,  tags: ['Meeting','Work'],     hi: false },
      { title: 'Set up product analytics with Mixpanel',        desc: 'Instrument key events: signup, first task, first focus session.',        est: 60,  tags: ['Work','Research'],    hi: false },
      { title: 'Review and approve marketing landing page',     desc: 'Check messaging accuracy and feature parity with current product.',      est: 30,  tags: ['Review','Work'],      hi: false },
      { title: 'User research synthesis: scheduling feature',   desc: 'Affinity mapping from 12 interviews. Prioritize top pain points.',       est: 90,  tags: ['Research','Planning'], hi: false },
      { title: 'Write acceptance criteria for v2.4 tickets',    desc: 'Cover happy path, edge cases and error states for all new features.',    est: 60,  tags: ['Work','Review'],      hi: false },
      { title: 'Quarterly board presentation prep',             desc: 'Slides, metrics and narrative for investor update.',                      est: 120, tags: ['Work','Urgent'],      hi: true  },
      { title: 'Run NPS survey: May cohort',                    desc: 'Send survey, analyse responses, present top themes.',                    est: 45,  tags: ['Research','Work'],    hi: false },
      { title: 'Define v3.0 beta access criteria',              desc: 'Who gets early access? Define segment, process and communication plan.', est: 30,  tags: ['Planning','Work'],    hi: false },
      { title: 'Weekly team standup facilitation',              desc: 'Async update + blocker review. Keep to 15 minutes.',                    est: 20,  tags: ['Meeting','Work'],     hi: false },
    ],
    in_progress: [
      { title: 'Map user journey: free-to-paid conversion',    desc: 'End-to-end flow from signup to first subscription charge.',              est: 90,  tags: ['Research','Urgent'],  hi: true  },
      { title: 'A/B test: CTA button copy',                    desc: '"Start free" vs "Get started" — 2-week test, 50/50 split.',             est: 45,  tags: ['Creative','Work'],    hi: false },
      { title: 'Write technical spec for API v3',              desc: 'Collaborate with engineering lead on breaking changes and migration.',   est: 120, tags: ['Work','Planning'],    hi: true  },
      { title: 'Plan product launch event',                    desc: 'Venue, guest list, demo script, press kit and social content.',         est: 90,  tags: ['Planning','Meeting'],  hi: false },
      { title: 'Define mobile app MVP scope',                  desc: 'Which web features translate to mobile? Core-only for v1.',             est: 60,  tags: ['Work','Research'],    hi: false },
    ],
    pending: [
      { title: 'Roadmap review: H2 planning',                  desc: 'Align next 6 months with company strategy and resource capacity.',      est: 120, tags: ['Planning','Work'],    hi: true  },
      { title: 'Partner integration discovery: Slack',         desc: 'Technical requirements, API feasibility and user demand validation.',   est: 60,  tags: ['Research','Work'],    hi: false },
      { title: 'Write case study: enterprise customer win',    desc: 'Outcome-led story for sales enablement and marketing.',                est: 90,  tags: ['Creative','Work'],    hi: false },
      { title: 'Set up product feedback portal',              desc: 'Evaluate Canny vs Productboard vs custom Notion setup.',               est: 45,  tags: ['Planning','Research'],  hi: false },
      { title: 'Annual planning offsite agenda',              desc: 'Schedule, exercises and pre-read materials for 2-day offsite.',        est: 60,  tags: ['Planning','Meeting'],  hi: false },
      { title: 'Review data privacy compliance',              desc: 'GDPR, CCPA checklist. Flag gaps for legal review.',                    est: 45,  tags: ['Urgent','Review'],     hi: true  },
      { title: 'Interview panel: senior PM candidate',        desc: 'Prepare case study, questions and scoring rubric.',                    est: 60,  tags: ['Work','Meeting'],      hi: false },
      { title: 'Personalisation: user goal onboarding',       desc: 'Collect intent data at signup to personalise first-run experience.',   est: 90,  tags: ['Research','Creative'], hi: false },
    ],
  },

  student: {
    completed: [
      { title: 'Submit algorithms assignment: graph traversal',  desc: 'Implement DFS, BFS and Dijkstra. Submit via university portal.',       est: 120, tags: ['Study','Tech'],    hi: true  },
      { title: 'Read Chapter 7: Operating Systems',              desc: 'Process scheduling, memory management, virtual memory.',               est: 60,  tags: ['Study','Research'], hi: false },
      { title: 'Study for linear algebra midterm',               desc: 'Eigenvalues, eigenvectors, matrix decomposition.',                    est: 180, tags: ['Study','Urgent'],  hi: true  },
      { title: 'Lab report: distributed systems experiment',     desc: 'Analyse consensus algorithm behaviour under network partition.',      est: 90,  tags: ['Study','Tech'],    hi: false },
      { title: 'Group project meeting: web app architecture',    desc: 'Decide on tech stack, task assignments and sprint schedule.',         est: 60,  tags: ['Study','Planning'], hi: false },
      { title: 'Implement red-black tree in C++',                desc: 'Data structures assignment. Include full test suite.',               est: 150, tags: ['Study','Tech'],    hi: true  },
      { title: 'Research paper outline: privacy in LLMs',        desc: 'Section headings, key arguments and bibliography draft.',            est: 60,  tags: ['Research','Study'], hi: false },
      { title: 'Gym session: strength training',                 desc: 'Upper body day. 45 minutes. Track reps and weight.',                 est: 60,  tags: ['Health','Personal'], hi: false },
      { title: 'Apply to 3 internship positions',                desc: 'Google, Spotify and Zalando. Tailor CV and write cover letters.',    est: 120, tags: ['Urgent','Personal'], hi: true  },
      { title: 'Mock interview practice: LeetCode medium',       desc: '5 problems. Focus on dynamic programming and sliding window.',       est: 90,  tags: ['Study','Tech'],    hi: false },
      { title: 'Attend professor office hours: thesis topic',    desc: 'Discuss NLP research direction and literature gaps.',                est: 30,  tags: ['Study','Planning'], hi: false },
      { title: 'Semester registration: choose electives',        desc: 'Register for Machine Learning and Distributed Databases.',          est: 30,  tags: ['Planning','Urgent'], hi: false },
      { title: 'Study group: software engineering patterns',     desc: 'Cover SOLID, design patterns with 3 classmates.',                   est: 90,  tags: ['Study','Tech'],    hi: false },
      { title: 'Write reflection: internship applications',      desc: 'What worked, what to improve, next steps.',                        est: 20,  tags: ['Personal','Study'],  hi: false },
      { title: 'Update GitHub portfolio with new projects',      desc: 'Add README, screenshots and live demo links for 4 repos.',         est: 45,  tags: ['Tech','Creative'],  hi: false },
    ],
    in_progress: [
      { title: 'Thesis proposal: privacy-preserving NLP',       desc: 'Background, problem statement, methodology and timeline.',          est: 240, tags: ['Study','Research'], hi: true  },
      { title: 'Web app project: milestone 2 — backend API',    desc: 'RESTful API for task management app. 12 endpoints.',               est: 180, tags: ['Study','Tech'],    hi: true  },
      { title: 'Prepare final presentation: compiler design',   desc: 'Slides, demo, and walkthrough of lexer and parser implementation.', est: 90,  tags: ['Study','Urgent'],  hi: false },
      { title: 'Job application materials revision',            desc: 'Update CV with latest project, revise LinkedIn summary.',          est: 60,  tags: ['Personal','Urgent'], hi: false },
      { title: 'Learn Docker and containerisation',             desc: 'Udemy course. Complete sections 1–8 before project submission.',   est: 120, tags: ['Study','Tech'],    hi: false },
    ],
    pending: [
      { title: 'Final exam: computer networks',                  desc: 'OSI model, TCP/IP, routing protocols, congestion control.',        est: 180, tags: ['Study','Urgent'],  hi: true  },
      { title: 'Submit thesis proposal to supervisor',           desc: 'Must be approved before semester 6 starts.',                      est: 30,  tags: ['Study','Urgent'],  hi: true  },
      { title: 'Apply to exchange program: TU Delft',           desc: 'Gather transcripts, motivation letter, professor reference.',     est: 90,  tags: ['Planning','Urgent'], hi: true  },
      { title: 'Set up home study schedule for exam period',    desc: 'Block study, breaks and sleep using StartSmart.',                 est: 20,  tags: ['Planning','Health'], hi: false },
      { title: 'Buy textbooks for next semester',               desc: 'Machine Learning by Murphy, DDIA by Kleppmann.',                  est: 15,  tags: ['Study','Personal'],  hi: false },
      { title: 'Summer internship: prepare for day 1',          desc: 'Read company engineering blog, set up dev environment.',         est: 60,  tags: ['Work','Planning'],  hi: false },
      { title: 'Weekly run: 5k',                                desc: 'Morning run. Track pace and heart rate.',                        est: 35,  tags: ['Health','Personal'], hi: false },
      { title: 'Visit grandparents',                            desc: 'Sunday afternoon. Take photos for family album.',                 est: 120, tags: ['Personal','Health'], hi: false },
    ],
  },

  freelancer: {
    completed: [
      { title: 'Client A: Deploy v2.1 to production',            desc: 'Final QA passed. Tag release, update changelog, notify client.',   est: 45,  tags: ['Work','Urgent'],    hi: true  },
      { title: 'Invoice: Client B — May services',               desc: 'Bill 28 hours at $120/hr. Send via FreshBooks.',                   est: 20,  tags: ['Work','Planning'],  hi: false },
      { title: 'Client C: Fix checkout bug on mobile',           desc: 'iOS Safari: submit button triggers twice. Reproduce and patch.',  est: 60,  tags: ['Frontend','Urgent'], hi: true  },
      { title: 'Proposal: Client D e-commerce rebuild',          desc: 'Scope, timeline, tech stack and pricing. 3-month engagement.',    est: 90,  tags: ['Work','Creative'],  hi: false },
      { title: 'Set up Stripe subscriptions for SaaS client',   desc: 'Free/Pro/Enterprise tiers. Webhook handling and trial logic.',    est: 120, tags: ['Backend','Tech'],   hi: true  },
      { title: 'Quarterly taxes: estimated payment',             desc: 'Calculate Q2 income, deductions and estimated payment.',         est: 45,  tags: ['Urgent','Planning'], hi: true  },
      { title: 'Client B: Performance optimisation audit',       desc: 'Lighthouse score from 42 to 89. Images, JS bundles, caching.',   est: 90,  tags: ['Frontend','Tech'],  hi: false },
      { title: 'Update portfolio with 3 new case studies',       desc: 'Screenshots, outcomes, tech stack and testimonial quote.',       est: 60,  tags: ['Creative','Work'],  hi: false },
      { title: 'Contract review: new long-term client',          desc: 'Payment terms, IP ownership, scope of work and NDA.',            est: 30,  tags: ['Work','Urgent'],    hi: false },
      { title: 'Client A: User authentication overhaul',         desc: 'Migrate from sessions to JWTs. Magic link + social login.',      est: 150, tags: ['Backend','Tech'],   hi: true  },
      { title: 'Weekly client status updates',                   desc: 'Send progress emails to all 4 active clients.',                  est: 30,  tags: ['Work','Planning'],  hi: false },
      { title: 'Set up accounting in Wave',                      desc: 'Import bank statements, categorise 3 months of transactions.',   est: 45,  tags: ['Planning','Work'],  hi: false },
      { title: 'Client C: SEO implementation',                   desc: 'Meta tags, structured data, sitemap, robots.txt, OG images.',   est: 60,  tags: ['Frontend','Work'],  hi: false },
      { title: 'Technical blog post: API design principles',     desc: 'Publish on personal blog. Target 1200 words.',                   est: 90,  tags: ['Creative','Tech'],  hi: false },
      { title: 'Renew professional liability insurance',         desc: 'Compare 3 quotes. Annual renewal.',                              est: 30,  tags: ['Personal','Urgent'], hi: false },
      { title: 'Client D: Database schema design session',       desc: '3-hour discovery call. Define entities, relationships, indexes.', est: 180, tags: ['Backend','Work'],  hi: false },
      { title: 'Gym: leg day',                                   desc: 'Squat, deadlift, leg press. 1 hour.',                           est: 60,  tags: ['Health','Personal'], hi: false },
      { title: 'Networking event: Startup & Freelancers night',  desc: 'Bring business cards. Follow up within 24 hours.',              est: 120, tags: ['Work','Personal'],  hi: false },
    ],
    in_progress: [
      { title: 'Client D: Build e-commerce backend',             desc: 'Product catalogue, cart, checkout, order management APIs.',      est: 240, tags: ['Backend','Work'],   hi: true  },
      { title: 'Cold outreach: 10 potential clients',            desc: 'Personalised LinkedIn messages and portfolio emails.',           est: 60,  tags: ['Work','Planning'],  hi: false },
      { title: 'Client B: Admin dashboard v2',                   desc: 'Rebuild with React 18, add real-time charts and CSV export.',   est: 180, tags: ['Frontend','Tech'],  hi: false },
      { title: 'Client A: mobile app (React Native)',            desc: 'Feature parity with web app. Phase 1: auth + task list.',       est: 300, tags: ['Frontend','Urgent'], hi: true  },
      { title: 'Create course: Freelancing for Developers',      desc: 'Outline, slides and first 3 modules on pricing and proposals.', est: 120, tags: ['Creative','Work'],  hi: false },
      { title: 'Research: passive income through templates',     desc: 'Evaluate Envato, Gumroad for selling Figma/Tailwind templates.', est: 45, tags: ['Research','Creative'], hi: false },
    ],
    pending: [
      { title: 'Client E: Discovery call — fintech startup',     desc: 'Review requirements brief. Prepare technical questions.',       est: 60,  tags: ['Work','Planning'],  hi: false },
      { title: 'Annual business health check',                   desc: 'Revenue, expenses, top clients, growth rate vs last year.',     est: 90,  tags: ['Planning','Work'],  hi: false },
      { title: 'Upgrade development machine',                    desc: 'M4 MacBook Pro or build custom Thunderbolt workstation.',      est: 30,  tags: ['Planning','Tech'],   hi: false },
      { title: 'Client A: v2.2 — push notifications',           desc: 'Firebase Cloud Messaging. iOS + Android + web push.',           est: 90,  tags: ['Backend','Work'],   hi: false },
      { title: 'Read: Atomic Habits',                            desc: 'Focus on habit stacking and compound improvement systems.',    est: 180, tags: ['Personal','Health'], hi: false },
      { title: 'Annual retreat: digital nomad exploration',      desc: 'Research 3-month Bali base. Coworking spaces, visa, cost.',   est: 60,  tags: ['Personal','Planning'], hi: false },
      { title: 'Apply for business credit card',                 desc: 'Separate personal and business expenses. 2% cashback goal.',  est: 20,  tags: ['Planning','Urgent'], hi: false },
      { title: 'Build referral network with 5 other freelancers',desc: 'Overflow work partnerships. Define rates and process.',       est: 45,  tags: ['Work','Planning'],  hi: false },
    ],
  },

  designer: {
    completed: [
      { title: 'Design new onboarding flow in Figma',            desc: '12-screen flow. Reduce steps from 8 to 4. Prototype for test.', est: 180, tags: ['Design','Creative'], hi: true  },
      { title: 'User testing: dashboard redesign',               desc: '6 participants. Record, transcribe, synthesise findings.',      est: 90,  tags: ['Research','Design'], hi: false },
      { title: 'Create design system: colour & typography',      desc: 'Primary, secondary, semantic tokens. Document in Storybook.',  est: 120, tags: ['Design','Creative'], hi: false },
      { title: 'Deliver brand identity: startup client',         desc: 'Logo suite, colour palette, typeface, usage guidelines.',      est: 240, tags: ['Creative','Work'],  hi: true  },
      { title: 'Redesign mobile navigation (bottom tab bar)',    desc: 'Accessibility-first. Test with screen reader. A/B variants.',  est: 90,  tags: ['Design','Urgent'],  hi: true  },
      { title: 'Competitive UX teardown: 5 apps',               desc: 'Analyse IA, onboarding, empty states and micro-interactions.',  est: 60,  tags: ['Research','Design'], hi: false },
      { title: 'Present design proposals to client',             desc: '3 concepts: minimal, bold, editorial. Include rationale.',     est: 45,  tags: ['Work','Meeting'],   hi: false },
      { title: 'Illustration set: 15 product icons',             desc: 'Line-style, consistent stroke, 3 sizes, 2 themes.',           est: 120, tags: ['Creative','Design'], hi: false },
      { title: 'Accessibility audit: WCAG 2.2 AA',               desc: 'Colour contrast, focus indicators, keyboard nav, alt text.',  est: 90,  tags: ['Design','Urgent'],  hi: true  },
      { title: 'Write UX case study for portfolio',              desc: 'Challenge → process → outcome. Include metrics and learnings.', est: 90, tags: ['Writing','Creative'], hi: false },
      { title: 'Motion design: loading and success states',      desc: 'After Effects animations. Export as Lottie. 8 states.',       est: 60,  tags: ['Design','Creative'], hi: false },
      { title: 'Figma component library: form elements',         desc: 'Input, select, checkbox, radio, date picker. Auto-layout.',   est: 90,  tags: ['Design','Work'],    hi: false },
      { title: 'Client feedback round: landing page',            desc: 'Collect, prioritise and schedule changes from 3 stakeholders.', est: 30, tags: ['Work','Review'],    hi: false },
      { title: 'Workshop: jobs-to-be-done with product team',   desc: 'Facilitate 90-min session. Synthesise into design brief.',    est: 90,  tags: ['Meeting','Research'], hi: false },
      { title: 'Weekly design critique with team',               desc: 'Review 4 pieces of work. Give and receive structured feedback.', est: 45, tags: ['Work','Meeting'],  hi: false },
    ],
    in_progress: [
      { title: 'Redesign pricing page: conversion-focused',      desc: 'Experiment with value-first layout and social proof placement.', est: 120, tags: ['Design','Urgent'],  hi: true  },
      { title: 'Create micro-animation library',                 desc: 'Hover, click, transition and loading states. 20 components.',  est: 180, tags: ['Creative','Design'], hi: false },
      { title: 'Develop personal brand: new portfolio site',     desc: 'Design in Figma, build in Framer. Launch before July.',       est: 240, tags: ['Creative','Personal'], hi: true  },
      { title: 'Email campaign: welcome sequence redesign',      desc: '5-email flow. New templates matching updated brand guidelines.', est: 90, tags: ['Design','Work'],    hi: false },
      { title: 'Research: generative AI in design workflow',     desc: 'Evaluate Midjourney, Adobe Firefly and Uizard for daily use.', est: 60, tags: ['Research','Design'], hi: false },
    ],
    pending: [
      { title: 'Pitch new client: e-commerce rebrand',           desc: 'Prepare moodboard, case studies and pricing proposal.',       est: 90,  tags: ['Work','Creative'],  hi: false },
      { title: 'Join Figma community: publish UI kit',           desc: 'Package component library and publish for free download.',    est: 45,  tags: ['Creative','Planning'], hi: false },
      { title: 'Workshop: UX writing for non-writers',           desc: 'Run 60-min internal workshop on microcopy principles.',       est: 90,  tags: ['Work','Writing'],   hi: false },
      { title: 'Update design resume and LinkedIn',              desc: 'Add 2025–2026 work. Rewrite bio to focus on outcomes.',      est: 45,  tags: ['Personal','Planning'], hi: false },
      { title: 'Mentoring session: junior designer',             desc: 'Monthly 1:1. Portfolio review and career path discussion.',  est: 60,  tags: ['Work','Meeting'],   hi: false },
      { title: 'Buy new drawing tablet',                         desc: 'Research Wacom vs Huion. Check compatibility with M3.',      est: 20,  tags: ['Planning','Personal'], hi: false },
      { title: 'Read: Hooked by Nir Eyal',                      desc: 'Apply habit loop model to product design decisions.',        est: 120, tags: ['Research','Personal'], hi: false },
      { title: 'Submit talk proposal: UX Summit 2026',           desc: 'Topic: "From pixels to outcomes: measuring UX impact".',    est: 45,  tags: ['Work','Urgent'],    hi: false },
    ],
  },
};

// ── Reflection pool (randomly assigned to completed tasks) ────────────────────
export const REFLECTIONS = [
  'Finished ahead of schedule — good estimation this time.',
  'Took longer than expected due to unexpected complexity. Will add buffer next time.',
  'Very focused session. No distractions. This is the flow state I should aim for.',
  'Had to pause halfway for an unplanned meeting. Lost 20 minutes of context.',
  'Underestimated the research phase. Actual was 40% over estimate.',
  'Collaboration made this faster — pair programming cut the time in half.',
  'Should have broken this into smaller tasks. Got blocked for 30 minutes.',
  'Perfect outcome. My estimation is improving for this type of task.',
  'Unexpected edge case took extra time. Worth documenting for future reference.',
  'Completed in a single focused block — no breaks needed.',
  'Started late in the day — energy was low. Morning would have been better.',
  'The prep work I did yesterday paid off. Very smooth execution.',
  'External dependency caused delay. Out of my control but should plan for it.',
  'This type of task consistently runs 25% over. Build that in next time.',
  'Really satisfied with this result. Quality was worth the extra time.',
  'Interrupted 3 times. Deep work needs protected time blocks.',
  'Finished in exactly the estimated time. Great week for estimation accuracy.',
  'Took a break mid-task which helped me see the solution more clearly.',
  'Realised halfway through I was solving the wrong problem. Pivoted correctly.',
  'Good session overall. Minor scope creep added about 15 minutes.',
  null, null, null, // some tasks have no reflection
];

// ── Notification templates ────────────────────────────────────────────────────
export const NOTIFICATION_TEMPLATES = [
  { type: 'reminder',    title: 'Task due soon',             body: 'Don\'t forget: "{title}" is scheduled for today.' },
  { type: 'time_gap',    title: 'Time gap detected',         body: 'Your focus session for "{title}" ran 25 min over estimate.' },
  { type: 'reminder',    title: 'Weekly goal progress',      body: 'You\'ve logged 4h 30m this week — 75% of your 6h goal.' },
  { type: 'system',      title: 'Welcome to StartSmart!',    body: 'Your workspace is all set. Start by adding your first task.' },
  { type: 'time_gap',    title: 'Focus session complete',    body: 'Great work! You stayed on task for 90 minutes straight.' },
  { type: 'reminder',    title: 'Daily summary',             body: 'You completed 3 tasks today and logged 2h 45m of focus time.' },
  { type: 'system',      title: 'New feature: Insights',     body: 'Check out your new Insights dashboard for personalised productivity trends.' },
  { type: 'time_gap',    title: 'Excellent estimation!',     body: 'Your last task was within 5 minutes of your estimate. Keep it up!' },
  { type: 'reminder',    title: 'Unstarted task',            body: '"{title}" has been pending for 3 days. Ready to start today?' },
  { type: 'system',      title: 'Weekly report ready',       body: 'Your week in review: 12 tasks completed, 5h 20m focus time, -8 min average gap.' },
  { type: 'reminder',    title: 'Streak milestone',          body: '🔥 5-day productivity streak! You\'ve hit your daily goal every day this week.' },
  { type: 'time_gap',    title: 'Long session detected',     body: 'You\'ve been in focus mode for 2+ hours. Consider taking a short break.' },
];
